[General]
ipv6 = false
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, fe80::/10, fc00::/7, localhost, *.local, *.lan, *.internal
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query

[Proxy]
jp-reality-01 = vless, jp01.example.com, 443, username=d342d11e-d424-4583-b36e-524ab1f0afa4, udp-relay=true, tls=true, flow=xtls-rprx-vision, peer-name=www.example.com, public-key=PBK_REPLACE_ME, skip-cert-verify=false
sg-reality-02 = vless, sg02.example.com, 443, username=d342d11e-d424-4583-b36e-524ab1f0afa4, udp-relay=true, tls=true, flow=xtls-rprx-vision, peer-name=www.example.com, public-key=PBK_REPLACE_ME, skip-cert-verify=false
us-reality-03 = vless, us03.example.com, 443, username=d342d11e-d424-4583-b36e-524ab1f0afa4, udp-relay=true, tls=true, flow=xtls-rprx-vision, peer-name=www.example.com, public-key=PBK_REPLACE_ME, skip-cert-verify=false

[Proxy Group]
Select = select, Fallback, Auto, jp-reality-01, sg-reality-02, us-reality-03
Auto = url-latency-benchmark, jp-reality-01, sg-reality-02, us-reality-03, url=http://www.gstatic.com/generate_204, interval=600
Fallback = available, jp-reality-01, sg-reality-02, us-reality-03, url=http://www.gstatic.com/generate_204, interval=600

[Rule]
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/private.txt,Direct
RULE-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/lancidr.txt,Direct,no-resolve
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/reject.txt,Reject
RULE-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/security.txt,Reject
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/icloud.txt,Direct
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/apple.txt,Direct
RULE-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/telegramcidr.txt,Select,no-resolve
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/google.txt,Select
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/gfw.txt,Select
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/greatfire.txt,Select
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/tld-not-cn.txt,Select
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/proxy.txt,Select
DOMAIN-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/direct.txt,Direct
RULE-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/cncidr.txt,Direct,no-resolve
RULE-SET,https://cdn.jsdelivr.net/gh/nuln/proxy-rules@shadowrocket/china_ip_list.txt,Direct,no-resolve
GEOIP,CN,Direct
FINAL,Direct
